//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: auxil/Card.java
//
//  Created by dst3708 on 4/1/13.
//


@interface Card : NSObject
{
  NSString *text;
  int matchID;
}

@property (nonatomic) NSString *text;
@property (nonatomic) int matchID;

@end
