//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: auxil/Card.java
//
//  Created by dst3708 on 4/1/13.
//

#import "Card.h"

@implementation Card

@synthesize text;
@synthesize matchID;

@end
